### ISSUE TITLE
Startseite und Menü modifizieren

### ISSUE THREAD

**Issue by Lelidle** [Willibald-Gluck-Gymnasium/wgg-homepage#198]
Alle Kacheln außer Highlights entfernen. 

Highlights oberhalb von Terminen. 

Dadurch mehr Fokus auf Suchfunktion legen, nicht "Durchscrollen fördern". 

Menü: 
- Events, Schulteam und Schulprofil sollen auch jeweils Artikel mit nur diesem Tag zeigen, nicht nur alles darunter zusammenfassen. 
- Alle Projekte entfernen
- Bei Unterricht Für Sprachen, Naturwissenschaften etc. gleiches Verhalten wie für Events, etc. herstellen, da sonst uneindeutig
- "Für Eltern" auch eine Oberkategorie "Überblick" einführen und ebenfalls an obige Vorgaben angleichen.

**Comment by alexanderhorner** [comment]
- [ ] Alle Kacheln außer Highlights entfernen (fixed in #203)
- [ ] Highlights oberhalb von Terminen
- [ ] Events, Schulteam und Schulprofil sollen auch jeweils Artikel mit nur diesem Tag zeigen, nicht nur alles darunter zusammenfassen.
- [ ] Alle Projekte entfernen
- [ ] Bei Unterricht Für Sprachen, Naturwissenschaften etc. gleiches Verhalten wie für Events, etc. herstellen, da sonst uneindeutig
- [ ] "Für Eltern" auch eine Oberkategorie "Überblick" einführen und ebenfalls an obige Vorgaben angleichen.

**Comment by Lelidle** [comment]
Kommt das letzte noch? Sonst schmeiße ich es bei Gelegenheit mal selbst raus.
